/**
 * Multiple Choice Questions: "Moby Dick" by Herman Melville
 * Source: Project Gutenberg (gutenberg.org) - Book #2701
 * Generated by Papersaurus AI Educational Tools
 * 
 * Each question has 5 options (A-E) with exactly one correct answer.
 * See answers.js for detailed explanations of all options.
 */

const questions = [
  {
    "id": 1,
    "question": "What is the famous opening line of Moby-Dick?",
    "options": {
      "A": "It was a dark and stormy night at sea.",
      "B": "Call me Ishmael.",
      "C": "I am a man of the ocean.",
      "D": "The whale surfaced at dawn.",
      "E": "In the beginning, there was the sea."
    },
    "correctAnswer": "B"
  },
  {
    "id": 2,
    "question": "To whom did Herman Melville dedicate Moby-Dick?",
    "options": {
      "A": "Ralph Waldo Emerson",
      "B": "Edgar Allan Poe",
      "C": "Nathaniel Hawthorne",
      "D": "Walt Whitman",
      "E": "Henry David Thoreau"
    },
    "correctAnswer": "C"
  },
  {
    "id": 3,
    "question": "What type of whale is Moby Dick?",
    "options": {
      "A": "Blue whale",
      "B": "Humpback whale",
      "C": "Right whale",
      "D": "Sperm whale",
      "E": "Gray whale"
    },
    "correctAnswer": "D"
  },
  {
    "id": 4,
    "question": "Which major theme does Captain Ahab's relentless pursuit of Moby Dick primarily represent?",
    "options": {
      "A": "The benefits of teamwork and cooperation",
      "B": "Destructive obsession and monomaniacal vengeance",
      "C": "The joy of maritime exploration",
      "D": "Romantic love and devotion",
      "E": "The importance of economic prosperity"
    },
    "correctAnswer": "B"
  },
  {
    "id": 5,
    "question": "In what year was Moby-Dick first published?",
    "options": {
      "A": "1845",
      "B": "1849",
      "C": "1851",
      "D": "1860",
      "E": "1891"
    },
    "correctAnswer": "C"
  },
  {
    "id": 6,
    "question": "How was Moby-Dick received upon its initial publication?",
    "options": {
      "A": "It was an immediate bestseller and critical triumph",
      "B": "It was a commercial failure and was out of print by Melville's death",
      "C": "It was banned in several countries for controversial content",
      "D": "It won major literary awards and widespread acclaim",
      "E": "It was only published posthumously"
    },
    "correctAnswer": "B"
  },
  {
    "id": 7,
    "question": "Which literary influences are reflected in the diverse styles used throughout Moby-Dick?",
    "options": {
      "A": "Homer, Virgil, and Dante",
      "B": "Shakespeare, the Bible, and Thomas Carlyle",
      "C": "Jane Austen, Charles Dickens, and the Brontës",
      "D": "Mark Twain, Harriet Beecher Stowe, and Louisa May Alcott",
      "E": "Voltaire, Rousseau, and Montesquieu"
    },
    "correctAnswer": "B"
  },
  {
    "id": 8,
    "question": "When did Moby-Dick become widely recognized as a Great American Novel?",
    "options": {
      "A": "Immediately upon publication in 1851",
      "B": "During the American Civil War in the 1860s",
      "C": "In the 20th century, following the 1919 centennial of Melville's birth",
      "D": "After a famous film adaptation in 1925",
      "E": "During Melville's celebrated lecture tours in the 1880s"
    },
    "correctAnswer": "C"
  },
  {
    "id": 9,
    "question": "Who is the narrator of Moby-Dick?",
    "options": {
      "A": "Captain Ahab",
      "B": "Starbuck",
      "C": "Queequeg",
      "D": "Ishmael",
      "E": "Herman Melville himself in first person"
    },
    "correctAnswer": "D"
  },
  {
    "id": 10,
    "question": "Beyond adventure and whaling, which broader subjects does Moby-Dick explore?",
    "options": {
      "A": "Astronomy, mathematics, and engineering",
      "B": "Class, morality, and religion",
      "C": "Cooking, fashion, and architecture",
      "D": "Botany, geology, and chemistry",
      "E": "Music theory, painting, and sculpture"
    },
    "correctAnswer": "B"
  }
];

module.exports = { questions };
